_class               = "class"
extends           = "extends"
implements    = "implements"
static               = "static"
abstract          = "abstract"
interface         = "interface"
int                     = "int"
synchronized = "synchronized"
